name: fc

on:
  push:
    branches:
      - master

jobs:
  update-befc-version:
    runs-on: ubuntu-latest
    steps:
      # https://github.com/actions/setup-node
      - name: install node
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: install serverless-devs
        run: npm install -g @serverless-devs/s

      # https://github.com/actions/setup-go
      - uses: actions/setup-go@v5
        with:
          go-version: "1.22"
          
      # https://help.aliyun.com/document_detail/295913.html
      - name: deploy
        working-directory: ./src/fcbe/container-copier
        run: |
          s config add --AccountID ${{secrets.AccountID}} --AccessKeyID ${{secrets.FC_ACCESS_KEY_ID}} --AccessKeySecret ${{secrets.FC_ACCESS_KEY_SECRET}} -a default

          s deploy